# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Aakarshitha Suresh"
resume_title:                   "SOC Design Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "aakarshitha.s@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "8148529802"
resume_contact_address:         ""

resume_header_contact_info:     "aakarshitha.s@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "SoC Design Engineer with 2+ years in RTL, SoC integration, and verification for ARM chips. Skilled in SystemVerilog, UVM, Python, and ASIC toolflows. Took lead on RTL/SoC design, automation, and lint/CDC closure with a focus on quality and efficiency. Passionate about growing in ASIC design and AI hardware, driven to create high-performance, intelligent systems that make an impact."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Aakarshitha"
  resume_twitter_url:           ""
  resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/aak-sur/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "aakarshitha.github.io/"
  resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
# resume_theme:                   default
theme: bulma-clean-theme

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
# Trigger rebuild
